default:
	$(MAKE) -C y_min_boundary
	$(MAKE) -C two_laser_independence
	$(MAKE) -C interpolation_accuracy
	$(MAKE) -C edge_behaviour
	$(MAKE) -C phase_override

clean:
	$(MAKE) -C y_min_boundary          clean
	$(MAKE) -C two_laser_independence  clean
	$(MAKE) -C interpolation_accuracy  clean
	$(MAKE) -C edge_behaviour          clean
	$(MAKE) -C phase_override          clean
