default:
	$(MAKE) -C run_A_tilt_and_file
	$(MAKE) -C run_B_file_only
	$(MAKE) -C run_C_tilt_no_file

clean:
	$(MAKE) -C run_A_tilt_and_file  clean
	$(MAKE) -C run_B_file_only     clean
	$(MAKE) -C run_C_tilt_no_file  clean
